stages:
  - test
  - build
  - deploy

test_deploy:
  stage: deploy
  image: $CI_REGISTRY/255/255-ansible-vcd
  variables:
    ANSIBLE_OPTIONS: "feature_name=$CI_COMMIT_REF_SLUG fronting_host=web-demo-$CI_COMMIT_REF_SLUG webhost_dns=$CI_COMMIT_REF_SLUG.172.24.131.122.xip.io state_fe_be_entry=absent"
    ANSIBLE_FORCE_COLOR: "true"
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIV_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ansible-playbook -i platform/inventories/dcsg/inventory --extra-vars "$ANSIBLE_OPTIONS ansible_sudo_pass=$APP_SUDO_PASSWORD" --user administrator platform/deploy_devlab.yml
  environment:
    name: $CI_COMMIT_REF_SLUG
    action: stop


#      ansible-playbook -i ansible/staging/devlab/inventory/ \ --extra-vars "$ANSIBLE_OPTIONS ansible_sudo_pass=$APP_SUDO_PASSWORD" \ --user ansibleuser \ ansible/app.yml


#ansible-playbook -i ansible/staging/devlab/inventory/ --extra-vars "$ANSIBLE_OPTIONS ansible_sudo_pass=$PROXY_SUDO_PASSWORD" --user administrator \ ansible/proxy.yml
