stages:
  - test
  - build
  - deploy

run_unit_tests:
  stage: test
  tags:
    - mvn
  script:
    - mvn -f build/pom.xml test

build_app:
  stage: build
  tags:
    - mvn
  script:
    - mvn -f build/pom.xml package
  artifacts:
    expire_in: 1 day
    paths:
      - build/api-admin/target/*.war
      - build/webservice/target/*.war
      - build/database/target/*.tar.gz

test_deploy:
  stage: deploy
  image: $CI_REGISTRY/255/255-ansible-vcd
  variables:
#    ANSIBLE_OPTIONS: "feature_name=$CI_COMMIT_REF_SLUG fronting_host=web-john-web-vm"
    ANSIBLE_FORCE_COLOR: "true"
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIV_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - echo "****** This is pissing me off *****"
    - echo $SSH_PRIV_KEY
    - echo $APP_SUDO_PASSWORD
    - ansible-playbook --key-file=$SSH_PRIV_KEY -i platform/inventories/dcsg/inventory --extra-vars "ansible_sudo_pass=$APP_SUDO_PASSWORD" --user administrator platform/deploy_devlab.yml -vvvv


