build_app:
  stage: build
  tags:
    - mvn
  script:
    - mvn -f build/pom.xml package
  artifacts:
    expire_in: 1 day
    paths:
      - build/api-admin/target/*.war
      - build/webservice/target/*.war
