---

# Wildfly groups
wildfly_user: wildfly
wildfly_group: wildfly
wildfly_admin_user: '{{ wildfly_secret_admin_user }}'
wildfly_admin_password: '{{ wildfly_secret_admin_password }}'


# Vagrant IP addresses
wildfly_ip_address: 10.0.0.6
mariadb_ip_address: 10.0.0.7
httpd_ip_address: 10.0.0.3

mariadb_host: 10.0.0.7

# Fix this

local_user: administrator
local_group: administrator

#ansible_ssh_private_key_file: key.pem


dns_domain: .172.24.131.122.xip.io

certificates_path: "tls/"

configure_selinux: no
