---

# Wildfly groups
wildfly_user: wildfly
wildfly_group: wildfly
wildfly_admin_user: '{{ wildfly_secret_admin_user }}'
wildfly_admin_password: '{{ wildfly_secret_admin_password }}'


mariadb_db_name: database
mariadb_root_password: password
maria_db_user: user


mariadb_bind_address: 10.0.0.7
wildfly_ip_address: 10.0.0.6
httpd_ip_address: 10.0.0.3
#WTF?
mariadb_host: 10.0.0.7

path_to_sql: build/database/target/

# Fix this

local_user: administrator
local_group: administrator

#ansible_ssh_private_key_file: key.pem
