---

- hosts: app
  become: yes
  user: administrator
  roles:
    - common
    - wildfly
    - datasource

- hosts: web
  become: yes
  user: administrator
  roles:
    - httpd

- hosts: dat
  become: yes
  user: administrator
  roles:
    - mysql
    - flyway
