---

- hosts: app
  become: yes
  user: administrator
  roles:
    - common
    - wildfly
    - datasource

#- hosts: web
#  become: yes
#  roles:
#    - httpd
#
#- hosts: dat
#  become: yes
#  roles:
#    - mysql
#    - flyway
