---
#TODO: tidy this up!
- hosts: app
  become: yes
  user: administrator
  roles:
    - common
    - wildfly
    - datasource
  tasks:
    - name: Deploy App
      copy:
        src: ../build/api-admin/target/api-admin.war
        src: ../build/webservice/target/webservice.war
        dest: /opt/wildfly/standalone/deployments/


- hosts: web
  become: yes
  user: administrator
  roles:
    - httpd

- hosts: proxy
  become: yes
  user: administrator
  roles:
    - haproxy

- hosts: dat
  become: yes
  user: administrator
  roles:
    - mysql
    - flyway

