---

# -------------------
# Config
# -------------------

#TODO: FIX this up

#- name: Install server config file
#  template:
#    src: etc_my.cnf.d_server.cnf.j2
#    dest: "{{ mariadb_config_server }}"
#  notify: restart mariadb
#  tags: mariadb

- name: Install network config file
  template:
    src: etc_my.cnf.d_network.cnf.j2
    dest: "{{ mariadb_config_network }}"
  notify: restart mariadb


# -------------------
# Root user / secure installation
# -------------------

# This command will fail when the root password was set previously
- name: Check if root password is set
  shell: >
    mysqladmin -u root status
  changed_when: false
  failed_when: false
  register: root_pwd_check


- name: Set MariaDB root password for the first time
  mysql_user:
    name: root
    password: "{{ mariadb_root_password }}"
    host: '{{ item }}'
    priv: '*.*:ALL'
    state: present
  with_items:
    - '{{ mariadb_host }}'
    - 127.0.0.1
    - ::1
    - 10.0.0.1
    - '{{ mariadb_ip_address }}'
    - 10.0.0.6
    - localhost
  when: root_pwd_check.rc == 0


- name: Remove the test database
  mysql_db:
    name: test
    login_user: root
    login_password:  "{{ mariadb_root_password }}"
    state: absent


- name: Remove anonymous users
  mysql_user:
    name: ''
    host_all: yes
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    state: absent

# -------------------
# Set up user
# -------------------
#TODO: fix this up
#- mysql_user:
#    name: john
#    password: password
#    priv: '*.*:ALL'
#    login_user: root
#    login_password: "{{ mariadb_root_password }}"
#    state: present


#- name: Copy the root credentials as .my.cnf file
#  template: src=root.cnf.j2 dest=~/.my.cnf mode=0600

