---

- name: "Ensure Flyway install path exists"
  file:
    path: "{{ flyway_install_root }}"
    state: directory
    mode: "u=rwX,go=rX"


- name: "Check if Flyway is already installed"
  stat:
    path: "{{  flyway_core_jar }}"
  register: __flyway_core_jar_stat


- name: "Check if Flyway is already installed"
  stat:
    path: "{{ flyway_core_jar }}"
  register: flyway_exists


- block:
    - name: "Download Flyway archive"
      get_url:
        url: "{{ flyway_url }}"
        dest: "{{ flyway_install_root }}/tmp_flyway.tar.gz"

    - name: "Extract Flyway archive"
      unarchive:
        src: "{{ flyway_install_root }}/tmp_flyway.tar.gz"
        dest: "{{ flyway_install_root }}"
        remote_src: yes

    - name: "Remove Flyway archive"
      file:
        path: "{{ flyway_install_root }}/tmp_flyway.tar.gz"
        state: absent

  when: flyway_exists.stat.exists == False

- name: "Ensure Flyway script is executable"
  file:
    path: "{{ flyway_script }}"
    mode: "ugo+x"

- name: "Ensure Flyway symblink exist"
  file:
    src: "{{ flyway_script }}"
    dest: "{{ flyway_symblink }}"
    state: link

#- name: "Ensure Flyway config file exists"
#  template:
#    src: "flyway.conf.j2"
#    dest: "{{ flyway_config_file }}"
#    mode: "u=rw,og=r"
