---

# Wildfly groups
wildfly_user: wildfly
wildfly_group: wildfly
wildfly_admin_user: '{{ wildfly_secret_admin_user }}'
wildfly_admin_password: '{{ wildfly_secret_admin_password }}'

# Vagrant IP addresses
wildfly_ip_address: 10.255.255.2
mariadb_ip_address: 10.255.255.4
httpd_ip_address: 10.255.255.11
