---

# Create wildfly user and group
- block:
    - name: Create Wildfly group
      group:
        name: '{{ wildfly_user }}'
        state: present

    - name: Create Wildfly User
      user:
        name: '{{ wildfly_user }}'
        group: '{{ wildfly_group }}'
        createhome: no
        system: yes
        state: present
        shell: /sbin/nologin
        state: present

#download wildfly
- name: Download Wildfly
  get_url:
    validate_certs: no
    url: '{{ wildfly_download_url }}'
    dest: '{{ wildfly_download_dir }}/{{ wildfly_download_file }}'
    timeout: 120


- name: Extract WildFly
  unarchive:
    src: '{{ wildfly_download_dir }}/{{ wildfly_download_file }}'
    remote_src: yes
    dest: '/opt'
    owner: '{{ wildfly_user }}'
    group: '{{ wildfly_group }}'
    creates: '{{ wildfly_dir }}/bin/standalone.sh'

- name: Create versionless symlink to WildFly install directory
  file:
    state: link
    src: '/opt/wildfly-11.0.0.Final'
    dest: '/opt/wildfly'
