---

httpd_user: apache
httpd_group: apache
apache_service: httpd

apache_restart_state: restarted
apache_state: started

apache_restart_state: restarted
apache_conf_dest: /etc/httpd/conf/httpd.conf
apache_ssl_conf_dest: /etc/httpd/conf.d/ssl.conf


httpd_packages:
  - httpd
  - mod_ssl
