---

#- name: Add official MariaDB repository
#  yum_repository:
#    name: MariaDB
#    description: Official MariaDB repository
#    baseurl: "http://yum.mariadb.org/{{ mariadb_version }}/{{ ansible_distribution|lower|regex_replace('redhat', 'rhel') }}{{ ansible_distribution_major_version }}-amd64"
#    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
#    gpgcheck: yes
#  tags: mariadb

- name: Install MariaDb
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - mariadb
    - mariadb-server

- name: Install the Python MySQL Support Libraries
  yum:
    pkg: MySQL-python
    state: latest

- name: start mysql server and enable it on reboot
  service:
    name: mariadb
    state: started
    enabled: yes
