---

- name: Install MariaDb
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - mariadb
    - mariadb-server

- name: Install the Python MySQL Support Libraries
  yum:
    pkg: MySQL-python
    state: latest

- name: start mysql server and enable it on reboot
  service:
    name: mariadb
    state: started
    enabled: yes
