---

- name: Check if root password is set
  shell: >
    mysqladmin -u root status
  changed_when: false
  failed_when: false
  register: root_pwd_check

# Note: 10.0.0.1 is so intellj or mysql developer can connect
# TODO: not entirely sure about this, come back to it later! Could copy over root credentials as .cnf file?
#- name: Set MariaDB root password for the first time
#  mysql_user:
#    name: root
#    password: "{{ mariadb_root_password }}"
#    host: '{{ item }}'
#    priv: '*.*:ALL'
#    state: present
#  with_items:
#    - 127.0.0.1
#    - ::1
#    - 10.0.0.1
#    - '{{ mariadb_bind_address }}'
#    - localhost
#  when: root_pwd_check.rc == 0


- name: Set MariaDB root password for the first time
  mysql_user:
    name: root
    password: "{{ mariadb_root_password }}"
    host_all: yes
    state: present
  when: root_pwd_check.rc == 0
  tags: mariadb
