---

# Wildfly groups
wildfly_user: wildfly
wildfly_group: wildfly
wildfly_admin_user: '{{ wildfly_secret_admin_user }}'
wildfly_admin_password: '{{ wildfly_secret_admin_password }}'

mariadb_root_password: password


# Vagrant IP addresses
wildfly_ip_address: 10.255.255.2
mariadb_ip_address: 10.255.255.4
httpd_ip_address: 10.255.255.11

mariadb_host: vagrant.grad.fun.dis.nz

local_user: vagrant
local_group: vagrant
